# Error Handling 
예외처리 


```python
a = 12 / 0 
```


    ---------------------------------------------------------------------------

    ZeroDivisionError                         Traceback (most recent call last)

    Input In [1], in <cell line: 1>()
    ----> 1 a = 12 / 0
    

    ZeroDivisionError: division by zero



```python
try : #에러가 예상되는 코드
    a = 12 / 0 
except: 
    print('Error!!!')
```

    Error!!!
    


```python
try : #에러가 예상되는 코드
    a = 12 / 0 
except: 
    pass #에러가 나도 그냥 지나가겠다. 
```


```python
try : #에러가 예상되는 코드
    a = 12 / 0 
except Exception as e: 
    print('에러의 원인은 ', e) #에러의 종류를 e가 가지고 있다.  
```

    에러의 원인은  division by zero
    
